# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  buildering:
    docker:
      - image: circleci/node:10.13.0-browsers
    working_directory: ~/repo
    environment:
      CI: true
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: yarn start
      
      # - run: ls -laR /home/circleci/repo/node_modules/puppeteer/.local-chromium
      # - run: yarn add puppeteer -D --force --verbose
    
      # start and test the app
      # - run: ./ci.sh

  testering:
    docker:
      - image: circleci/node:10.13.0-browsers
    working_directory: ~/repo
    environment:
      CI: true
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: yarn test --maxWorkers 2 

workflows:
  version: 2
  build_and_test:
    jobs:
      - buildering
      - testering:
        requires:
          - buildering
